# ビルド環境
FROM node:18.1-alpine AS BUILD-STAGE
WORKDIR /frontend
COPY package.json .
RUN npm install 
COPY . .
RUN apk update && \
    npm install -g npm

# テスト環境
FROM nginx:1.17.4-alpine as TEST-STAGE
RUN rm /etc/nginx/conf.d/default.conf
COPY default.test.conf /etc/nginx/conf.d
COPY --from=BUILD-STAGE /frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]