version: "3.7"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"