version: "3.7"

services:
  # backend:
  #   container_name: backend
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8080:8080"
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    tty: true #コンテナを起動し続けるオプション
    # stdin_open: true
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
  # nginx:
  #   container_name: nginx
  #   build: ./nginx
  #   depends_on:
  #     - backend
  #     - frontend
  #   ports:
  #     - "80:80"