version: "3.7"

services:

  db:
    container_name: db
    build:
      context: ./db
    

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ${DOCKERFILE}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    tty: true

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ${DOCKERFILE}
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ${DOCKERFILE}
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"