openapi: 3.0.2
info:
  title: OpenAPI
  version: 0.0.0

paths:
  /api/auth:
    get:
      tags:
        - auth
      responses:
        '200':
          description: サーバーは正常に動作しています
  /api/signup:
    post:
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: サーバーは正常に動作しています
  /api/login:
    post:
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: サーバーは正常に動作しています
  /api/auth/logout:
    post:
      tags:
        - user
      responses:
        '200':
          description: サーバーは正常に動作しています
  /api/auth/users:
    get:
      tags:
        - user
      responses:
        '200':
          description: サーバーは正常に動作しています
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginUserResponse'
  /api/memories:
    get:
      tags:
        - memory
      responses:
        '200':
          description: サーバーは正常に動作しています
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicMemoryResponse'
  /api/auth/memories:
    get:
      tags:
        - memory
      responses:
        '200':
          description: サーバーは正常に動作しています
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyMemoryResponse'
    post:
      tags:
        - memory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoryRequest'
      responses:
        '201':
          description: サーバーは正常に動作しています

  /api/auth/memories/{id}:
    put:
      tags:
        - memory
      parameters:
        - $ref: '#/components/parameters/MemoryId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoryRequest'
      responses:
        '204':
          description: サーバーは正常に動作しています
    delete:
      tags:
        - memory
      parameters:
        - $ref: '#/components/parameters/MemoryId'
      responses:
        '204':
          description: サーバーは正常に動作しています

components:
  parameters:
    MemoryId:
      name: id
      in: path
      description: メモリーID
      required: true
      schema:
        type: integer
  schemas:
    UserRequest:
      type: object
      properties:
        name:
          type: string
        password:
          type: string
      required:
        - name
        - password
    MemoryRequest:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        isPublic:
          type: boolean
    LoginUserResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    PublicMemoryResponse:
      type: object
      properties:
        memories:
          items:
            $ref: '#/components/schemas/PublicMemory'
      required:
        - memories
    MyMemoryResponse:
      type: object
      properties:
        memories:
          items:
            $ref: '#/components/schemas/MyMemory'
      required:
        - memories
    PublicMemory:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        isPublic:
          type: boolean
        userName:
          type: string
      required:
        - id
        - title
        - description
        - createdAt
        - isPublic
        - userName
    MyMemory:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        isPublic:
          type: boolean
      required:
        - id
        - title
        - description
        - createdAt
        - isPublic